### ISSUE TITLE
Consider using Gateway.spec.infrastructure labels/annotations fields

### ISSUE THREAD

**Issue by jenshu** [kgateway-dev/kgateway#10821]
Gateways now have an [infrastructure](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.GatewayInfrastructure) field, which allows users to specify `labels` and `annotations` to apply to all dynamically provisioned proxy resources. Consider using the new fields instead of, or in addition to, the currently supported [GatewayParameters fields](https://github.com/kgateway-dev/kgateway/blob/main/api/v1alpha1/kube_types.go).

Things to consider:
- Note that currently, labels and annotations for Pods, Services, and ServiceAccounts can each be configured independently via GatewayParameters, whereas the Gateway.spec.infrastructure field would apply the same set of labels/annotations to all proxy resources. If we use Gateway.spec.infrastructure, should that be considered a base set of labels/annotations for all resources, that can be further customized per-resource via GatewayParameters? Would we merge or overwrite (or should we deprecate/remove the GWP fields and only use infrastructure)?
- There would be a slight UX change, where proxy config would now live in 2 places: labels/annotations would live on the Gateway spec, and other config would live in GatewayParameters. Is this acceptable?

**Comment by timflannagan** [comment]
Need to enable the conformance test for the labels/annotations as well.

**Comment by howardjohn** [comment]
Big +1. Very frustrating to use a field in a v1 resource and have it silently ignored

**Comment by jenshu** [comment]
reopening because it's only fixed in agentgateway

**Comment by PedroRibeiro95** [comment]
I see this has been supposedly closed in https://github.com/kgateway-dev/kgateway/pull/12735, but I don't think it has been released as of 2.1.2 I still can't use `spec.infrastructure.annotations`. Can we expect it to be released in 2.2.0?

**Comment by timflannagan** [comment]
@PedroRibeiro95 Yeah, https://github.com/kgateway-dev/kgateway/commit/d7b40f99e3a0837d69db4d79c96e859caab6afa5 has only been tagged with 2.2 releases so far and missed the 2.1 cutoff. You can try using one of the 2.2.0-beta releases until 2.2 is formally released. IIRC, we're targeting 2.2 GA sometime next month.

**Comment by PedroRibeiro95** [comment]
Thanks for the clarification @timflannagan and for the great work on this tool!
