### ISSUE TITLE
Enforce order of plugins

### ISSUE THREAD

**Issue by lgadban** [kgateway-dev/kgateway#11446]
- BackendTLSPolicy
- BackendConfigPolicy.TLS

Other cases as well
- Istio plugin with TLS

**Comment by timflannagan** [comment]
@lgadban what's the driver where we need explicit plugin ordering?

**Comment by ymesika** [comment]
I opened https://github.com/kgateway-dev/kgateway/pull/12176 as an immediate solution to opt-out of Istio plugin's socket matchers and have BCP/BTP take place.

I think a driver for this @timflannagan is to have a priority for BTP/BCP over Istio so that if we see that Transport Socket is already exist when Istio plugin is executed, we can avoid adding the Istio Transport Socket Matchers. This way we don't need the opt-out annotation.
Does it make sense?

**Comment by josh-pritchard** [comment]
@ymesika have you added a README to a PR for this?

**Comment by ymesika** [comment]
Added to https://github.com/kgateway-dev/kgateway/pull/12176 :

https://github.com/kgateway-dev/kgateway/blob/f1d68868a71a8bdc143ac4a3d0e49ac56aaeffda/docs/tls-configuration-ordering.md

**Comment by ymesika** [comment]
Document of current (no) order of plugins has been added in: https://github.com/kgateway-dev/kgateway/pull/12176
We still don't enforce specific order and if we do then the annotation to disable auto-mtls will be redundant.

Question is if there are reasons other than the Istio auto-mtls to enforce an order.

**Comment by shashankram** [comment]
> Question is if there are reasons other than the Istio auto-mtls to enforce an order.

When multiple plugins implement the same policy, we need ordering to make the output deterministic. Otherwise, it would break policy usage.

**Comment by lgadban** [comment]
>When multiple plugins implement the same policy, we need ordering to make the output deterministic. Otherwise, it would break policy usage.

I honestly don't fully understand this statement. Can you elaborate on how multiple plugins can implement the same policy? 

Given the plugins/policy are associated with a singular GK, I'm missing how we can have more than one implementation.

**Comment by shashankram** [comment]
> > When multiple plugins implement the same policy, we need ordering to make the output deterministic. Otherwise, it would break policy usage.
> 
> I honestly don't fully understand this statement. Can you elaborate on how multiple plugins can implement the same policy?
> 
> Given the plugins/policy are associated with a singular GK, I'm missing how we can have more than one implementation.

- built-in httproute policies and TrafficPolicy have overlap
- BackendConfigPolicy, BackendTLSPolicy, Istio auto-mTLS have overlap

without their application order being deterministic, the system will have unexpected behavior on reconciliations

**Comment by josh-pritchard** [comment]
We should fix this, there should never be non-deterministic outputs.

**Comment by lgadban** [comment]
I'm still not convinced it's a matter of deterministic plugin ordering.

IIUC the overlap described above is more that several different plugins can operate on the same Envoy output.
I do agree that we should definitely get this well defined and understood though.
